// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("aggregator")>]
[<assembly: AssemblyProductAttribute("aggregator")>]
[<assembly: AssemblyVersionAttribute("1.3.1")>]
[<assembly: AssemblyFileVersionAttribute("1.3.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "aggregator"
    let [<Literal>] AssemblyProduct = "aggregator"
    let [<Literal>] AssemblyVersion = "1.3.1"
    let [<Literal>] AssemblyFileVersion = "1.3.1"
    let [<Literal>] AssemblyConfiguration = "Release"
